### PR TITLE
Adding postgres example for database

### PR DESCRIPTION
**Pull request by vsoch**
This will add an example for the user to run a docker postgres container and then use the drift-server! I've tested this locally and all works, so I think this will help us to go back and debug the kubernetes setup.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by alecbcs** [comment]
Wooo! Glad you got this working so quickly!

**Comment by vsoch** [comment]
I do think there are subtle difference between what I got working and what we were trying - the separation characters are different, and I did wind up specifying the database name to the container (which means it was created, I'm not sure we did that in our recipes). I am also wondering if ssl is required / enabled by default and without deploying the ceritificates.yaml if we get that out of the box? Anyhoo, I think we can at least more confidently debug now that we know what works!

**Comment by alecbcs** [comment]
Awesome! Should be try merging this and bringing the system back up on the cluster?

**Comment by vsoch** [comment]
yes!

**Pull request merged**
